### ISSUE TITLE
`Rename` in generated migration has incorrect table `:prefix`

### ISSUE THREAD

**Issue by fredwu** [ash-project/ash_postgres#104]
**Describe the bug**

When you rename a field for a resource that has a table prefix, the generated migration file contains incorrect rename syntax.

**To Reproduce**

Rename a resource that has a table prefix.

**Expected behavior**

Expected outcome:

```elixir
rename table(:finance_orders, prefix: "v2"), :source, to: :provider
```

Actual / incorrect outcome:

```elixir
rename table(:finance_orders), :source, to: :provider, prefix: "v2"
```

** Runtime
 - Elixir version 1.13.4
 - Erlang version 24.3.4
 - OS MacOS 12.5
 - Ash version 1.52.0-rc.21
 - Ash Postgres 0.42.0-rc.7

**Comment by zachdaniel** [comment]
Thanks for the report! I've pushed a fix
