### ISSUE TITLE
Extensions missing when generating migrations

### ISSUE THREAD

**Issue by totaltrash** [ash-project/ash_postgres#106]
**Describe the bug**
I recently updated ash_postgres to the latest, and now I seem to be getting no extensions added to the install_extensions migration. Previously I would get:

```elixir
  def up do
    execute("CREATE EXTENSION IF NOT EXISTS \"uuid-ossp\"")
    execute("CREATE EXTENSION IF NOT EXISTS \"pg_trgm\"")
    execute("CREATE EXTENSION IF NOT EXISTS \"citext\"")
  end
```
Now I'm getting
```elixir
  def up do
  end
```

** Runtime

 - ash 1.53.3
 - ash_postgres 0.43.0

**Comment by zachdaniel** [comment]
Fixed in 0772c6ea2d1cdab135825d7fc07ccf537c7c9c8f
