### ISSUE TITLE
Index in migration generated by Resource identity does not honour column order

### ISSUE THREAD

**Issue by fredwu** [ash-project/ash_postgres#109]
**Describe the bug**

The index generated by `mix ash_postgres.generate_migrations` contains incorrect index column order.

**To Reproduce**

In an Ash resource we have:

```elixir
identities do
  identity :user_new_order, [:user_id, :money, :executed_at]
end
```

**Expected behavior**

Expected index:

```elixir
create unique_index(:test, [:user_id, :money, :executed_at],
         name: "test_user_new_order_index"
       )
```

Actual index:

```elixir
create unique_index(:test, [:executed_at, :money, :user_id],
         name: "test_user_new_order_index"
       )
```

** Runtime
 - Elixir version 1.14.0
 - Erlang version 25.0.4
 - OS macOS 12.5.1
 - Ash version 2.0.0-rc.0
 - Ash postgres 1.0.0-rc.0

**Comment by zachdaniel** [comment]
Yeah, interesting. So what we do currently is we sort the keys alphabetically, I presume to do some checking on key equality. But that shouldn't be necessary.

**Comment by zachdaniel** [comment]
Yeah, everywhere I can see we are sorting the keys before comparing them, so it should just be safe to remove that sort :)

**Comment by zachdaniel** [comment]
Alright, will be fixed in main shortly. Remember, however, that main on all of the projects are set up for ash 2.0, so you'll have to upgrade all of your extensions if you haven't already.

**Comment by zachdaniel** [comment]
Thanks for the report!
