### ISSUE TITLE
Respond with a more useful error message if required Postgres extensions are missing

### ISSUE THREAD

**Issue by sevenseacat** [ash-project/ash_postgres#112]
**Is your feature request related to a problem? Please describe.**
Yes - I was recently experimenting with how to do partial text matches, and came across the `contains` predicate. I finally got the syntax how I think it's supposed to work, but it raised an error because I didn't have the `citext` extension enabled.

```
iex(2)> MyApp.Element |> Ash.Query.filter(contains(description, "oil")) |> MyApp.Api.read()
[debug] QUERY ERROR source="elements" db=0.0ms queue=0.4ms idle=808.3ms
SELECT e0."id", e0."description", FROM "elements" AS e0 WHERE (strpos(e0."description"::citext, $1::citext) > 0) ["oil"]
[error] Task #PID<0.668.0> started from #PID<0.665.0> terminating
** (Postgrex.Error) ERROR 42704 (undefined_object) type "citext" does not exist

    query: SELECT e0."id", e0."description" FROM "elements" AS e0 WHERE (strpos(e0."description"::citext, $1::citext) > 0)
    ...
```

**Describe the solution you'd like**
Ideally there would be a nicer error message, something like "The `citext` extension needs to be installed before the `contains/2` predicate can be used. Please add `citext` to the list of `installed_extensions` in your Repo module."

**Comment by zachdaniel** [comment]
Solved in v1.0.0-rc.6
