### ISSUE TITLE
filters break when using the join assoc of a many to many to filter

### ISSUE THREAD

**Issue by michaelst** [ash-project/ash_postgres#123]
the issue happens when introducing an or to the filter clause

`Database |> Ash.Query.filter(restrict_access == false or users_join_assoc.user_id == ^user.id)`

![image](https://user-images.githubusercontent.com/4080508/207213793-5e74ccb8-b642-4bfd-bc48-2bec5e017f08.png)

**Comment by zachdaniel** [comment]
This one is weird too 😆 It looks like its actually the sort that is causing this problem. I just had a though, do you have any sorts on relationships that might be coming into play? Or default sorts on resources?

**Comment by zachdaniel** [comment]
Fixed in main!
