### ISSUE TITLE
Treatment of the `/` operator in expr

### ISSUE THREAD

**Issue by scflode** [ash-project/ash_postgres#128]
**Describe the bug**

I have a calculation on a resource looking like this:

```
  calculations do
    calculate :percent_open,
              :float,
              expr(if(total_tickets > 0, open_tickets / total_tickets, 100.0))
  end
```
that leads for the true case to `0.0`.

**To Reproduce**

Create a resource with the given calculation. (Example is taken from the getting started guide)

**Expected behavior**

The calculation should return the proper value without casting the type (see below).

** Runtime
 - Elixir version: 1.14.3
 - Erlang version: 25.2.1
 - OS: macOS 13.2
 - Ash version 2.5.9
 - AshPostgres version: 1.3.3
 - Postgres version: 14.5

**Additional context**

The workaround for this is:

```
  calculations do
    calculate :percent_open,
              :float,
              expr(if(total_tickets > 0, type(open_tickets / total_tickets, :float), 100.0))
  end
```

See also https://discord.com/channels/711271361523351632/1068191797056118784

**Comment by zachdaniel** [comment]
Hey there @scflode could you try out main and see if you can remove the explicit typecasting? Thanks :D

**Comment by scflode** [comment]
Will do ASAP (maybe only by tomorrow).

**Comment by scflode** [comment]
@zachdaniel It works with main. The calculation is done correctly without the need to type cast. Thanks for the quick fix!

**Comment by zachdaniel** [comment]
@arduino-man please create a reproduction or PR a failing test and I will take a look.

**Comment by zachdaniel** [comment]
Can you please open a separate issue as well so I can track the status? Thank you.
