### ISSUE TITLE
Preparation does not work on a calculation, except when its parameters are cast as strings

### ISSUE THREAD

**Issue by waseigo** [ash-project/ash_postgres#130]
**Describe the bug**

Preparation does not work on a calculation, except when its parameters are cast as strings.

**To Reproduce**

The following is a part of resource `App.Api.Item`.
A Variant `has_one` Item, and `belongs_to` Family, which `belongs_to` Category.

```elixir
  relationships do
    belongs_to :variant, App.Api.Variant
  end

  aggregates do
    first :variant_code, :variant, :code # refers to App.Api.Variant resource; :code is an :integer
    first :category_code, [:variant, :family, :category], :code # refers to App.Api.Category resource with a path through App.Api.Variant, App.Api.Family
  end

  calculations do
    calculate :code, :string, expr(category_code <> variant_code)
  end

  preparations do
    prepare build(load: [:category_code, :variant_code])
  end
```  

The above is OK. However, it fails when I add `:code` to the `prepare` statement:

```elixir
  preparations do
    prepare build(load: [:category_code, :variant_code, :code])
  end
```

```** (Postgrex.Error) ERROR 42883 (undefined_function) operator does not exist: bigint || bigint.```

However, it does work when I cast all parameters to a `:string`, like so:

```elixir
  calculations do
    calculate :code, :string, expr(type(category_code, :string) <> type(variant_code, :string))
  end
```

**Expected behavior**

The `:code` calculation should also be loaded in advance, even without casting each parameter of the calculation to `:string`.

**Runtime**
```
Erlang/OTP 25 [erts-13.1.3] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit:ns]
Elixir 1.14.0 (compiled with Erlang/OTP 24)
```
```
      {:ash, "~> 2.6.0"},
      {:ash_postgres, "~> 1.3.8"},
```

**Additional context**
Discussed with @zachdaniel on the [Ash Discord server](https://discord.com/channels/711271361523351632/1074303297072152586).

**Comment by zachdaniel** [comment]
Fixed in the latest main of ash & ash_postgres. Will be in the next releases of the two packages.
