### ISSUE TITLE
Migration generated when adding a reference can't be rolled back

### ISSUE THREAD

**Issue by sevenseacat** [ash-project/ash_postgres#139]
**Describe the bug**

This might be similar to the bug from #137 .

One of my resources defined a belongs_to relationship to another resource but didn't specify the cascade behaviour; I added it in with:

```diff
  postgres do
    table "experiments"
    repo Repo

    references do
+     reference :organisation, on_delete: :delete
    end
  end
```

And this generated the following migration:

```elixir
defmodule MyApp.Repo.Migrations.MigrateResources3 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  # up omitted for brevity

  def down do
    alter table(:experiments) do
      modify :organisation_id,
             references(:organisations,
               column: :id,
               prefix: "public",
               name: "experiments_organisation_id_fkey",
               type: :uuid
             )
    end

    drop constraint(:experiments, "experiments_organisation_id_fkey")
  end
end
```

The migration can be run forwards, but can't be rolled back afterwards:

```
14:56:35.472 [info] == Running 20230418065611 MyApp.Repo.Migrations.MigrateResources3.down/0 forward

14:56:35.476 [info] alter table experiments
** (Postgrex.Error) ERROR 42710 (duplicate_object) constraint "experiments_organisation_id_fkey" for relation "experiments" already exists
...
```

Because the commands are defined in the wrong order in the `down` definition - the old constraint should be removed before the new one is created.

**Expected behavior**

Generating the migration should create a migration that can run forwards and backwards repeatedly without error.

**Runtime**

 - Elixir version 1.14.3
 - Erlang version 25.2
 - OS MacOS Ventura
 - Ash version 2.6.31
 - AshPostgres main at 525dcc9f911712c512598e0a7bef415b26fddc8d

**Comment by sevenseacat** [comment]
Interestingly, I actually needed a migration to fix *two* references and they were generated differently - 

```elixir
  def down do
    # This one will work
    drop constraint(:instance_logs, "instance_logs_instance_id_fkey")

    alter table(:instance_logs) do
      modify :instance_id,
             references(:instances,
               column: :id,
               prefix: "public",
               name: "instance_logs_instance_id_fkey",
               type: :uuid
             )

      # I don't even know where this came from, the column has not changed
      modify :associated_email, :text
    end

    # This one won't work
    alter table(:experiments) do
      modify :organisation_id,
             references(:organisations,
               column: :id,
               prefix: "public",
               name: "experiments_organisation_id_fkey",
               type: :uuid
             )
    end

    drop constraint(:experiments, "experiments_organisation_id_fkey")
  end
```

**Comment by zachdaniel** [comment]
Interesting...so I think what might be happening is a non deterministic sorting. I was having trouble with the original sorting algorithm so I switched it to use digraph, and without the proper dependency, it could sometimes come out in the right order and sometimes in the wrong. Thanks for the report :) will take a look

**Comment by zachdaniel** [comment]
```
      # I don't even know where this came from, the column has not changed
      modify :associated_email, :text
```

This is concerning.

**Comment by sevenseacat** [comment]
That one might be a separate issue - I have a field `associated_email` which is text, and I added an association that also uses it as a lookup field. 

```elixir
    belongs_to :user, MyApp.Accounts.User do
      api MyApp.Accounts
      source_attribute :associated_email
      destination_attribute :email
    end
```

Adding the association is what caused the migration to add `modify :associated_email, :text` to both `up` and `down`.

**Comment by zachdaniel** [comment]
Could it be because the default field type for `belongs_to` is `:uuid`? Is the `up` migration changing the field type to `:uuid`? You might want `attribute_type :string`.

**Comment by sevenseacat** [comment]
Maybe. No, both, are setting it to text - 

```
  def up do
    alter table(:instance_logs) do
      modify :associated_email, :text
    end
  end

  def down do
    alter table(:instance_logs) do
      modify :associated_email, :text
    end
  end
```

**Comment by zachdaniel** [comment]
Very strange. I'll have to look into both of these when I get a chance.

**Comment by zachdaniel** [comment]
Pushing a fix for the unrollback-able migration. Still not sure on the unnecessary attribute migration, but we'll just have to leave that for another issue :)

**Comment by zachdaniel** [comment]
I believe I've just found and fixed the other issue as well :)
