### ISSUE TITLE
Generated migrations should be formatted correctly

### ISSUE THREAD

**Issue by joshprice** [ash-project/ash_postgres#163]
**Describe the bug**

When generating migrations the Elixir formatter complains that the generated migration is not formatted correctly.

**To Reproduce**

In an Ash resource, add a field.

Generate a migration with `mix ash_postgres.generate_migrations --name x`

Run `mix format --check-formatted`

The following error is generated:

```
** (Mix) mix format failed due to --check-formatted.
The following files are not formatted:

  * priv/repo/migrations/20230815073951_x.exs 
```

Formatting and diffing the result shows that a trailing newline is missing and added by the formatter:

```diff
-end
\ No newline at end of file
+end
```

**Expected behavior**

Expect a correctly formatted migration file with no errors from a format check.

**Runtime**

 - Elixir 1.14.4-otp-25
 - Erlang 25.3.2
 - macOS
 - Ash/ Ash Postgres: main

**Comment by zachdaniel** [comment]
Fixed in adac811c797d51e158faa2609488e21433d444f0
