### ISSUE TITLE
Allow layering of Repos

### ISSUE THREAD

**Issue by ahacking** [ash-project/ash_postgres#172]
## It is not possible to layer/compose Repo modules

Ash currently assumes Ecto.Repo is the repository to use when this may not be the case.

A good use case is the fly.io support for distributed Postgres which provides a different Repo implementation.

### One solution is to provide repo as an option

This would allow setting up the fly.io Postgres repo and passing to Ash.

So we could setup fly Postgres:

```elixir
defmodule MyApp.Repo.Local do
  use Ecto.Repo,
    otp_app: :my_app,
    adapter: Ecto.Adapters.Postgres

  @env Mix.env()

  # Dynamically configure the database url based on runtime and build
  # environments.
  def init(_type, config) do
    Fly.Postgres.config_repo_url(config, @env)
  end
end

defmodule MyApp.Repo.Fly do
  use Fly.Repo, local_repo: MyApp.Repo.Local
end
```

And now with Ash:
```elixir
# in lib/helpdesk/repo.ex

defmodule MyApp.Repo do
  use AshPostgres.Repo, repo: MyApp.Repo.Fly
end
```

### A better way is to just get out of the way

Remove the use Ecto.Repo here:

https://github.com/ash-project/ash_postgres/blob/41c34b8777777a116ea87fe93d3b5603ef9ac030/lib/repo.ex#L68

Then you would just Add the ash line and leave the users use Ecto.Repo (or equivalent) alone:

```elixir
# in lib/helpdesk/repo.ex

defmodule MyApp.Repo do
  use Fly.Repo, local_repo: MyApp.Repo.Local
  use AshPostgres.Repo
end
```

Or regular repo:

```elixir
defmodule MyApp.Repo do
    use Ecto.Repo,
      otp_app: :my_app,
      adapter: Ecto.Adapters.Postgres
  use AshPostgres.Repo
end
```

### Suggestion

Make the ```:otp_app``` keyword optional and when not passed  don't call use Ecto.Repo  and therfore inherit the users existing ```use Ecto.Repo``` or equivalent setup. This should be backward compatible.

**Comment by zachdaniel** [comment]
I think we will need to add `define_ecto_repo?: false` as an option or something. Even if we aren't the ones calling `use Ecto.Repo` we still need the otp app. I'd need to check and make sure our changes are compatible with flys changes.

**Comment by ahacking** [comment]
Yeah I did review the code and the only use of otp_app was for ```use Ecto.Repo```, however if there is a future requirement this might be too fragile.

I would be happy with your option proposal ```define_ecto_repo?: false``` however you still may need to finesse whether opt_app is _really_ needed or not.
