### ISSUE TITLE
Calc to agg from calc to agg in separate resource errors

### ISSUE THREAD

**Issue by lifeofdan** [ash-project/ash_postgres#178]
**Describe the bug**
When doing a calculation on an aggregate that uses a calculation from an aggregate in a separate resource an error is thrown. 

<img width="982" alt="image" src="https://github.com/ash-project/ash_postgres/assets/1669918/97ece9a2-57db-4ef9-b386-f4eab7ee3ef0">

**To Reproduce**
A test case is available in this fork. https://github.com/lifeofdan/ash_postgres/tree/calculation-pass-actor

**Expected behavior**
Expected actor to be passed from calc to agg to calc to agg and receive the data from the original resource. In this case bubble up the description all the way from the `Profile` resource's description up to the `Post` resource's calculation.

** Runtime
 - Elixir version 1.15.4
 - Erlang version 26.0.2
 - OS MacOs
 - Ash version 2.17

**Comment by zachdaniel** [comment]
This was harder than I thought it was going to be 😆 Can you try `main` please? It should be fixed.

**Comment by lifeofdan** [comment]
@zachdaniel After pulling `main` I now have a different error. 
 
<img width="1051" alt="image" src="https://github.com/ash-project/ash_postgres/assets/1669918/d6b986ed-14f5-435f-8457-81a6913ff8e1">

**Comment by zachdaniel** [comment]
🤔 I've added the resource we're using to hydrate the expression, perhaps that will add some insight?

**Comment by lifeofdan** [comment]
That gives a little insight? It is the post resource, although that was probably already apparent. 
<img width="936" alt="image" src="https://github.com/ash-project/ash_postgres/assets/1669918/3de0bace-b264-43e0-980e-678fb0cadbde">

**Comment by zachdaniel** [comment]
This one is tough :) Still working on it.

**Comment by zachdaniel** [comment]
Going to take some time to address, will let you know when I've got it figured out.

**Comment by zachdaniel** [comment]
You know what...I just realized I've been chasing down something that we actually just don't currently support 😢 Specifically, aggregates can't use other aggregates as their `field`. In this case, it's an aggregate using a calculation that refers to an aggregate. I'd like to make this work, and it was always on the docket to do so, but it is quite complex and really amounts to an additional feature in some ways.

**Comment by lifeofdan** [comment]
So, if this doesn't work (which is fine, I understand this is a bit nested). Why does test "complex calculation while using actor on related resource passes reference" work? Isn't this a calc referring to an agg referring to a calc that refers to an agg? What is the big difference between these two?

**Comment by zachdaniel** [comment]
That one just happens to work I think 😆 It has to do with the fact that they are "first optimizable aggregates" AFAICT.

**Comment by lifeofdan** [comment]
Interesting. I'm glad our other use case works as it is much more important to us! 😄 

If you want to close this as `wontfix` that is okay. We will use another method to do what we need since this is not actually supported. My bad! Ty for your time on this. :)

**Comment by zachdaniel** [comment]
I'm going to see what I can do to make this work, but it may involve some changes in core and a bit more work :)

**Comment by zachdaniel** [comment]
AFAIK this is fixed :)
