### ISSUE TITLE
Error building reference

### ISSUE THREAD

**Issue by lifeofdan** [ash-project/ash_postgres#181]
**Describe the bug**
When trying to pass complex related data a reference to the original data is not being managed.
<img width="1060" alt="image" src="https://github.com/ash-project/ash_postgres/assets/1669918/b5f86bdd-4b32-4704-9597-3165845363bf">

**To Reproduce**
Here is a link to a test to reproduce the issue. https://github.com/lifeofdan/ash_postgres/tree/use_actor_from_complex_related_resource

**Expected behavior**
The data from the original resource should be passed along to the calculation. 

** Runtime
 - Elixir version 1.15.4
 - Erlang version 26.0.2
 - OS MacOs 14.1.1
 - Ash version 2.17

**Comment by zachdaniel** [comment]
Had to make some fixes to the commit you linked, but found the fix and pushed :)

**Comment by lifeofdan** [comment]
Thanks for that. Perfectly resolved now. :)
