### ISSUE TITLE
Migration bigint to bigserial, when generated? true added to attribute

### ISSUE THREAD

**Issue by hmy3743** [ash-project/ash_postgres#204]
**Describe the bug**
A clear and concise description of what the bug is. If you are not sure if the bug is related to `ash` or an extension, log it with [ash](https://github.com/ash-project/ash/issues/new) and we will move it.

Create migration with `attribute :id, :integer, allow_nil?: false, primary_key?: true`
then snapshot is
```
"attributes": [
    {
      "allow_nil?": false,
      "default": "nil",
      "generated?": false,
      "primary_key?": true,
      "references": null,
      "size": null,
      "source": "id",
      "type": "bigint"
    },
   #... 
]
```

And change attribute to
```
attribute :id, :integer do
  allow_nil? false
  primary_key? true
  generated? true
  writable? false
end
```
and run ash_postgres.generate_migrations to make migration then `modify :id, :bigint`

**To Reproduce**
A minimal set of resource definitions and calls that can reproduce the bug.
```
defmodule Core.Api.Resource do
  use Ash.Resource,
    data_layer: AshPostgres.DataLayer

  attributes do
    attribute :id, :integer do
      allow_nil? false
      primary_key? true
      # generated? true
      # writable? false
    end
    attribute :name, :string, allow_nil?: false
  end
```
make migration and uncomment two lines and make migration again with existing snapshot

**Expected behavior**
`modify :id, :bigserial`

** Runtime
 - Elixir version 1.16.1
 - Erlang version 26.2.1
 - OS 13.0(22A8380) macos ventura
 - Ash version 2.18.2
 - any related extension versions ash_postgres: 1.4.0

**Additional context**

Thanks 😄

**Comment by hmy3743** [comment]
If I delete every snapshot and make migration again, It gives `add :id, :bigserial, null: false, primary_key: true`.

**Comment by zachdaniel** [comment]
Thanks for the report:) This should be fixed in main.
