### ISSUE TITLE
Using an aggregrate on an attribute for a relation leads to inneficient queries

### ISSUE THREAD

**Issue by jeroen11dijk** [ash-project/ash_postgres#215]
Given this read query for my dossiers table which is linked to a details table:

```elixir
  aggregates do
    first :details_name, :details, :name
  end

    read :read_pagination do
      argument(:sort_direction, :atom, allow_nil?: false, default: :asc)

      prepare build(
                load: [
                  :details,
                  events: [:event_type, treatment: [:provider], dossier: [:details]]
                ],
                sort: [details_name: arg(:sort_direction)]
              )

      pagination offset?: true, default_limit: 10
    end

  relationships do
    has_one(:details, Cvs.Client.Details)
  end
```

Ash will run the following query:

```sql
SELECT
  d0."id"
FROM
  "dossiers" AS d0
  LEFT OUTER JOIN LATERAL (
    SELECT
      (array_agg(sd0."name" ::text)) [1] ::text AS "details_name",
      sd0."dossier_id" AS "dossier_id"
    FROM
      "public"."details" AS sd0
    WHERE
      (d0."id" = sd0."dossier_id")
    GROUP BY
      sd0."dossier_id"
  ) AS s1 ON TRUE
ORDER BY
  s1."details_name",
  d0."id"
LIMIT
  10
OFFSET
  0
```

This is a rather inefficient and slow query while something similar to should be what you expect:

```sql
 select d.id from dossiers d join details dd on d.id = dd.dossier_id
  ORDER BY
    dd.name,
    d.id
   LIMIT
    10
  OFFSET
    0
```

**Comment by jeroen11dijk** [comment]
I tried the last version of postgres to test expr_sort on the attribute of a relation which works perfectly. Yet when I tried this approach with the aggregate (which in this case wouldnt make sense) the query is now:

```sql
SELECT
  d0."id"
FROM
  "dossiers" AS d0
  LEFT OUTER JOIN LATERAL (
    SELECT
      sd0."dossier_id" AS "dossier_id",
      (array_agg(sd0."name" ::text)) [1] ::text AS "details_name"
    FROM
      "public"."details" AS sd0
    WHERE
      (d0."id" = sd0."dossier_id")
    GROUP BY
      sd0."dossier_id"
  ) AS s1 ON TRUE
ORDER BY
  s1."details_name" ::text ::text,
  d0."id"
LIMIT
  10
  ```
  
  Which is even less efficient, and is using the setup described in the issue.

**Comment by zachdaniel** [comment]
Right, I think that is an optimization that we can add at some point to essentially "flatten" out aggregates that reference each other. In the meantime, its advised to use a single aggregate with a relationship path:

```elixir
first :thing, [:relationship, :path, :to, :something, :else], :thing
```

**Comment by zachdaniel** [comment]
As long as each step along the way is not a to-many relationship, it should be done with regular joins.

**Comment by zachdaniel** [comment]
FYI in the latest version of ash_posgres, you will likely notice slightly more verbose queries as we have made some changes to leverage subqueries for internal simplicity. We tested a bunch of query plans and found no difference in the way that they are planned.
