### ISSUE TITLE
Warning shown unnecessarily when present validation specified in atomic action

### ISSUE THREAD

**Issue by ahey** [ash-project/ash_postgres#237]
**Describe the bug**
The following warning is incorrectly produced when a `present` validation is specified inside an atomic action. When the same validation is specified inside the validations block instead, the warning is not produced.

The warning produced at compile time:

```
warning: [AshPostgres.Test.Post]
 actions -> atomic_update_with_validation:
  `AshPostgres.Test.Post.atomic_update_with_validation` cannot be done atomically, because the changes `[Ash.Resource.Validation.Present]` cannot be done atomically

You must either address the issue or set `require_atomic? false` on `AshPostgres.Test.Post.atomic_update_with_validation`.

  test/support/resources/post.ex:16: AshPostgres.Test.Post.__verify_spark_dsl__/1
```

**To Reproduce**
[I have pushed a commit](https://github.com/ahey/ash_postgres/commit/40d73e69104fa79ef3fa8079485814cd9ed75a34) that reproduces the warning. Running the test suite produces the warning at compile time.

** Runtime
- ash `3.0.0-rc.24`
- ash_postgres `2.0.0-rc.7`

**Comment by zachdaniel** [comment]
This is fixed with latest ash main! I also noticed this today 😂

**Comment by ahey** [comment]
Thanks – I'm upgrading a small project to v3 as a test run before doing it on a larger project. So far so good!
