### ISSUE TITLE
Relationships Should Offer Index Support

### ISSUE THREAD

**Issue by allenwyma** [ash-project/ash_postgres#248]
**Is your feature request related to a problem? Please describe.**
Indexes are commonly used when finding records. It's common to find records by foreign key. Having an easy way to have this would be well-welcomed rather than the current way which is using `custom_indexes` option.

**Describe the solution you'd like**
belongs_to and other relationships should have an automatic index, with an option to turn off if so requested. This should be part of the relationship configuration, since it's dealing with the relationship.

**Describe alternatives you've considered**
It's something that happens automatically with ecto (if i remember correctly), and is something that would help with large datasets.

**Express the feature either with a change to resource syntax, or with a change to the resource interface**

Default:

```elixir
  relationships do
    belongs_to :author, Tweeter.Accounts.User do
      domain Tweeter.Accounts
      allow_nil? false
      # index? true
    end
  end
```

IF you want no index:

```elixir
```elixir
  relationships do
    belongs_to :author, Tweeter.Accounts.User do
      domain Tweeter.Accounts
      allow_nil? false
      index? false
    end
  end
```
```

**Comment by zachdaniel** [comment]
So, we won't be able to do it in the relationship like that as extensions can't patch the options of an entity (can't add `index?` to `belongs_to`).

What we could do is extend the `references`  configuration to have an `index?: true`

```elixir
postgres do
  references do
    reference :author, index?: true
  end
end
```

**Comment by allenwyma** [comment]
Can we have the option to turn on/off in postgres top level? and have the option for references? Cause usually i'd like to have default indexes.

**Comment by zachdaniel** [comment]
Like this?
```elixir
postgres do
  references do
     index? true
  end
end
```

**Comment by allenwyma** [comment]
yes, that's okay.

**Comment by allenwyma** [comment]
How about?
```elixir
postgres do
  references do
    index? false
    reference :author, index?: true
  end
end
```

so don't generate indexes, EXCEPT the author

**Comment by zachdaniel** [comment]
Yeah, thats definitely workable. I think we can start it as opt-in for now. Its not really a "breaking" change if we make it opt-out in the future as generating migrations is a dev-time operation, so they'd see the new operations and make up their mind at that point, but we can still leave it for a while and give people time to use it and what not.

**Comment by zachdaniel** [comment]
I've marked this as "good first issue", because it doesn't extend much beyond its scope, but I'd rate it as an intermediate issue.

**Comment by allenwyma** [comment]
> Yeah, thats definitely workable. I think we can start it as opt-in for now. Its not really a "breaking" change if we make it opt-out in the future as generating migrations is a dev-time operation, so they'd see the new operations and make up their mind at that point, but we can still leave it for a while and give people time to use it and what not.

but this is 3.0, we still got time to make a "breaking change" :)

**Comment by zachdaniel** [comment]
Maybe, but I keep squeezing things in, gotta draw the line somewhere 😆
