### ISSUE TITLE
Don't overwrite snapshots, store them w/ version numbers and create new ones

### ISSUE THREAD

**Issue by zachdaniel** [ash-project/ash_postgres#27]
Right now we overwrite snapshots, which causes a few problems. The most important is that if you haven't committed your changes between the last time you generated migrations, its very easy to get into an annoying/undesirable state.

**Comment by transhapHigsn** [comment]
Working on it.

**Comment by zachdaniel** [comment]
This was completed thanks to some work from @transhapHigsn and a few modifications I made after. Great job!
