### ISSUE TITLE
Generated migration for new join tables causes error when running migration

### ISSUE THREAD

**Issue by mvellandi** [ash-project/ash_postgres#28]
**Describe the bug**
When creating a new join table through a resource declaration, running the generated migration file causes an error message such as:
** (Postgrex.Error) ERROR 42P16 (invalid_table_definition) multiple primary keys for table "resource1_resource2" are not allowed
SOLUTION: After having generated a new join table call,
when generating an "alter table(resource1_resource2)" call for adding id -> resource references,
<img width="558" alt="sample_migration" src="https://user-images.githubusercontent.com/7730606/97626745-95da6a80-1a2a-11eb-96a7-7969e3d23699.png">

DO: remove id property modifications (notably: "primary_key: true")

**To Reproduce**
# Module definition, use Ash.Resource...
postgres do
    table "resource1_resource2"
    repo MyApp.Repo
  end

  relationships do
    belongs_to :resource1, Resource1, primary_key?: true
    belongs_to :resource2, Resource2, primary_key?: true
  end

**Expected behavior**
Migrations should run without error

** Runtime
 - Elixir version: 1.10.4
 - Erlang version: 23
 - OS: OSX Catalina
 - Ash version: 1.22
 - any related extension versions

**Additional context**

**Comment by zachdaniel** [comment]
Fixed in v0.25.4
