### ISSUE TITLE
parent does not work from within an aggregate filter 

### ISSUE THREAD

**Issue by kernel-io** [ash-project/ash_postgres#287]
When attempting to use `parent` from within an aggregates filter the following error is thrown
`Unsupported expression in Elixir.AshPostgres.SqlImplementation query: %{attribute: :queue_id, resource: nil, __struct__: Ash.Query.Ref, relationship_path: [], bare?: nil, input?: nil, simple_equality?: nil}`

The workaround is to place the `parent` within a filter defined on the relationship.

Expectation is that `parent` is available in all contexts.

```elixir
count :open_count, :transactions do
  filter expr(status != :completed and queue_id == parent(queue_id))
end
```

throws an error, a filter needs to be defined on the `transactions` relationship as such.

```elixir
filter expr(queue_id == parent(queue_id))
```

**Comment by zachdaniel** [comment]
🙇
