### ISSUE TITLE
Proposal for `ash_postgres.squash_snapshots` mix task

### ISSUE THREAD

**Issue by vonagam** [ash-project/ash_postgres#301]
The idea is simple - a task to clean up snapshots and remove all but last ones.

With usual flags `--check`, `--dry-run`, `--snapshot-path` and `--quiet`. Plus `--into` flag that can take `first`, `last` or `zero` and determines the name for a remaining snapshot (first, last are self-explanatory, zero means name with fourteen zeros).

The additional bonus of such task is that its usage (with `--into first` or `--into zero` and `--check` for CI) can help with problems currently present when multiple branches generate migrations and then get merged. The problems that #75 should fix. But unlike operations this task can be implemented quite trivially (and squashing will still make sense to have even after operations are in place).

This is a thing that I had proposed on Discord relatively recently. Just want to confirm the judgement on it. No pressure from me, if it does not fit in the official package I might do it as a separate package then.

**Comment by zachdaniel** [comment]
I'm happy to see the task exist 👍 It will be entirely different once operations exist, but the concept wouldn't go away.
