### ISSUE TITLE
The maximum length of the index name is not considered

### ISSUE THREAD

**Issue by nallwhy** [ash-project/ash_postgres#304]
**Describe the bug**
The maximum length of the index name is 63 in postgres.
When the index name set in Ash exceeds 63 characters, it is truncated to 63 characters when the index is created. In such cases, the actual index name differs from the one set in Ash, causing issues with unique constraint checks and migrations.

**To Reproduce**
Create identity with long name.

**Expected behavior**
Raise an error during compilation.

** Runtime
 - Elixir version: 1.16.1
 - Erlang version: 26
 - OS: mac
 - Ash version: 3.0.7
 - any related extension versions
   - ash_postgres: 2.0.5

**Additional context**

**Comment by ahey** [comment]
This postgres limitation has bitten me before too. Perhaps we could detect when the generated index name is greater than 63 characters, then create a base 16 encoded hash of the name instead? We could name it something like `"#{table_name_truncated_to_30_chars}_#{32_char_hash_of_full_index_name}"`

**Comment by zachdaniel** [comment]
So, index names in Ash for identities are configurable, so I think what we need to do is detect when an index name would be generated that is longer than 63 characters, and raise an error at compile time requiring that users override the name.
