### ISSUE TITLE
`Identity.where` is not working

### ISSUE THREAD

**Issue by jechol** [ash-project/ash_postgres#305]
**Describe the bug**
The Identity.where option is being ignored.

**To Reproduce**

For example,

```
  identities do
    identity :foo_bar, [:foo], where: :bar_is_ten
  end

  postgres do
    identity_wheres_to_sql [bar_is_ten: "bar = 10",  
                            foo_bar: "bar = 20"]
  end
```

This results in bar_is_ten being ignored, and it creates the following with where: "bar = 20" instead:

```
  create unique_index(:my_table, ["foo"], name: "foo_bar_index", where: "bar = 20")
```

**Expected behavior**

A migration with "bar = 10"

```
 create unique_index(:my_table, ["foo"], name: "foo_bar_index", where: "bar = 10")
```

**Comment by zachdaniel** [comment]
The keyword lists are not merged, you're meant to put them all in one call to the option.

**Comment by zachdaniel** [comment]
The way that you're writing it is incorrect. The key is the identity name and the value is the SQL where clause.

```elixir

identities do
    identity :foo_bar, [:foo], where: expr(bar == 10)
  end

  postgres do
    identity_wheres_to_sql [foo_bar: "bar = 10"]
  end

```

**Comment by jechol** [comment]
@zachdaniel 

So, the expression `expr(bar == 10)` in the where clause is not actually being used, right?

**Comment by zachdaniel** [comment]
It's not being used to generate the filter in Postgres cases, no. (Because we don't have an expr -> raw SQL converter yet), it's all Ecto expressions.
