### ISSUE TITLE
Removing an attribute generates a migration with commented out changes, but snapshot with the changes

### ISSUE THREAD

**Issue by sevenseacat** [ash-project/ash_postgres#307]
**Describe the bug**

I just found myself in this situation. Generating migrations after removing a few attributes from a resource (amongst other changes), it had a bunch of commented out code like this:

```elixir
def up do
  # alter table(:element_media_items) do
  # Attribute removal has been commented out to avoid data loss. See the migration generator documentation for more
  # If you uncomment this, be sure to also uncomment the corresponding attribute *addition* in the `down` migration
  # remove :description
  # end
  #
end

def down do
  # alter table(:element_media_items) do
  # This is the `down` migration of the statement:
  #
  #     remove :description
  #
  # 
  # add :description, :text
  # end
  # 
end
```

I didn't want to make these changes yet, and figured I didn't have to because there's a big old "*if* you uncomment this", so I deleted the comments.

Later on, when I *do* want to make these changes, I generated migrations again but there were no changes to make - the earlier migration had already generated a snapshot with the columns removed, despite the migration not actually removing the columns without intervention.

I've seen this before - people generate migrations and run them without checking them first, assuming they're doing exactly what was intended, and thus the snapshots end up out of sync with the actual database. Resetting the database won't help, either, because running all the migrations will have a different structure than the latest snapshot.

**Expected behavior**

This is a tricky one. I don't really get why the removal is commented out by default - maybe we don't do that?

Maybe we print out a big message after generating the migration saying HEY GO LOOK AT THE MIGRATION? But even that won't help, if people do what I did and remove the comments, thinking it's no big deal to delete a comment.

Do we flag the columns in the snapshot somehow, and then when running the migration, remove the columns (or clear the flags)?

Do we only generate snapshots when the migrations are run, not when they're generated?

I don't have a good answer here...

** Runtime

(don't think any of this is relevant but hey)

 - Elixir version 1.15.4-otp-26
 - Erlang version 26.0.2
 - OS macOS Sonoma
 - Ash version 2.21.14 (but confirmed it also happens in 3.0.4)
 - AshPostgres version 1.5.26 (but confirmed it also happens in 2.0.3)

**Comment by zachdaniel** [comment]
Yeah, I think we should just remove the commented out code concept TBH

**Comment by zachdaniel** [comment]
Or perhaps make it interactive and ask.

X column would be dropped. Your options are:

1. make the column nullable, so you can drop it yourself later (recommended) # only show this if its a required field currently
2. drop the column
3. comment it out

**Comment by zachdaniel** [comment]
Thoughts?

**Comment by sevenseacat** [comment]
The simplest thing would be to drop the column, that's what the diff says to do, after all.

Maybe we can display a big warning when generating migrations, if a column is being dropped, though? Devs probably should review migrations before running them anyway, IMO.

I mean, this is being run in dev first, and the dev database *should* be throwaway so if you di accidentally drop a column you didn't mean to, it shouldn't be a massive deal.

**Comment by zachdaniel** [comment]
Yeah, but people don't test rolling restarts in dev 🥶I think for now, lets just make it "do what it says on the tin", and then people can institute their own processes around migrations that remove things.
