### ISSUE TITLE
Migration generator doesn't consider generated?-flag on integer values 

### ISSUE THREAD

**Issue by Awlexus** [ash-project/ash_postgres#32]
**Describe the bug**
I created a migration for a resource with the following attribute
```elixir
attribute :id, :integer, primary_key?: true, generated?: true
```
But the migration didn't consider the `genrated?`-flag and created the field like this
```elixir
add(:id, :integer, null: true, default: nil, primary_key: true)
```

**Comment by zachdaniel** [comment]
Based on the attribute, we can assume `:serial` for integers if there is no default and if `generated?: true`
