### ISSUE TITLE
NaiveDateTime value breaks queries with Map type

### ISSUE THREAD

**Issue by dmitriid** [ash-project/ash_postgres#322]
**Describe the bug**

The way Map types are encoded has changed from passing the map to Postgres to calling `jsonb_build_object`. This breaks some on some values that were previously valid (or worked, even if invalid :) ). In my case it's `NaiveDateTime`.

That is, this can be fixed (I think) by providing type hints to the map type, but in this case the object is highly dynamic.

**To Reproduce**

Given

```
    attribute :settings, :map do
      allow_nil?(true)
      default(%{publish_at: :now})
    end

    update :update_settings do
      accept([:settings])
    end

    code_interface do
       define(:update_settings, args: [:settings])       
    end
```

We can see this by running the same code, `update_settings(%{publish_at: NaiveDateTime.utc_now()})`:

**{:ash, "~> 2.21"}**
**{:ash_postgres, "~> 1.5.23"}**
```
> Module.update_settings(%{publish_at: NaiveDateTime.utc_now()})

    UPDATE "pages" AS p0
    SET
        "updated_at" = $1::timestamp,
        "settings" = $2
     WHERE (p0."id"::uuid = $3::uuid)
     RETURNING ...

    [~U[2024-06-09 17:28:54.788191Z],
     %{publish_at: ~N[2024-06-09 17:28:54.787545]}, 
     "1f914e4c-6853-496d-bdb5-865b080811ed"]

OK
```

**{:ash, "~> 3.0.9"}**
**{:ash_postgres, "~> 2.0.6"}**

```
> Module.update_settings(%{publish_at: NaiveDateTime.utc_now()})

  UPDATE "pages" AS p0
  SET
      "updated_at" = $1::timestamp::timestamp,
      "settings" = (jsonb_build_object($2::varchar::varchar,($3)))
   WHERE (p0."id"::uuid = $4::uuid)
   RETURNING ...
   
   [~U[2024-06-09 17:14:41.654121Z], 
    :publish_at,
    ~N[2024-06-09 17:14:41.652560], 
    "1f914e4c-6853-496d-bdb5-865b080811ed"]


%Postgrex.Error{
   message: nil, 
   postgres: %{code: :indeterminate_datatype, line: "736", message: "could not determine data type of parameter $3"
}
```

**Runtime**
 - Elixir 1.16.2
 - Erlang/OTP 26 [erts-14.2.3]
 - Ubuntu 22.04.1 LTS
 - Ash 3.0.9
 - Ash Postgres 2.0.6

**Comment by zachdaniel** [comment]
@dmitriid this is definitely a problem :) The primary reason that this changed was because of the change to atomic updates. What I'm thinking we can do here is actually bypass the current logic if there are no nested expressions, which should solve for the case when setting the value to a literal value. I'll play with it and see if I can make that work.

**Comment by zachdaniel** [comment]
Okay @dmitriid I believe I've solved this in `main` of `ash_sql`. Please try it out and let me know. We can reopen the issue if it persists.

**Comment by dmitriid** [comment]
@zachdaniel Sorry, I only now got around to code.

It works!

`{:ash_sql, git: "git@github.com:ash-project/ash_sql.git", branch: "main", override: true}`

```
> Module.update_settings(%{publish_at: NaiveDateTime.utc_now()})

  UPDATE "pages" AS p0
  SET
      "updated_at" = $1::timestamp::timestamp,
      "settings" = $2 
  WHERE 
      (p0."id"::uuid = $4::uuid)
  RETURNING ...

  [~U[2024-06-11 11:50:24.668755Z],
   %{publish_at: ~N[2024-06-11 11:50:24.641755]}, 
   "1f914e4c-6853-496d-bdb5-865b080811ed"]

OK
```

**Comment by zachdaniel** [comment]
🥳

**Comment by dmitriid** [comment]
@zachdaniel There is a separate issue unrelated to this one though 🙈 I added it to `ash_sql` https://github.com/ash-project/ash_sql/issues/39

**Comment by zachdaniel** [comment]
Ah, right, interesting. We're going to need a way to tell it that we're encoding a literal 🤔 Or actually better yet is to give it the same treatment as maps, which is to use a literal list when its, well, a literal list.
