### ISSUE TITLE
integer_primary_key migration issue

### ISSUE THREAD

**Issue by totaltrash** [ash-project/ash_postgres#34]
**Describe the bug**

The migrator generates a non-incrementing, nullable field for `integer_primary_key`.

**To Reproduce**

An attribute defined as:

```elixir
integer_primary_key :id
```
generates:

```elixir
add(:id, :integer, null: true, default: nil, primary_key: true)
```

**Expected behavior**

```elixir
add(:id, :serial, null: false, primary_key: true)
```

**Comment by zachdaniel** [comment]
This is currently tracked in #32, thanks for reporting it in further detail!
