### ISSUE TITLE
Tenant migrations won't run without --domains

### ISSUE THREAD

**Issue by TobiasFroberg** [ash-project/ash_postgres#357]
**Describe the bug**
I was trying to migrate my context-based tenant migrations today but couldn't and it seems like there could possibly be a bug in `AshPostgres.Mix.Helpers` introduced in [this commit](https://github.com/ash-project/ash_postgres/commit/6b1f6bae2a3c0ddd57e9ef88d951156046695eb2).

If I just do `mix ash_postgres.migrate --tenants` I get nothing at all as output.
If I do supply `--domains MyApp.MyDomain` however, the migrations run.
I also ensured that I do have `config :my_app, ash_domains: [...]` set in my config

**To Reproduce**
* Generate a new tenant migration.
* Run `mix ash_postgres.migrate --tenants`
* Migration won't run

**Expected behavior**
I expect the migration to run

**Runtime**
 - Elixir 1.17.1 (compiled with Erlang/OTP 27)
 - ash_postgres version 2.1.12

**Comment by zachdaniel** [comment]
🤔 interesting. Oh, are your ecto repos in `config :my_app, ecto_repos: [...]`? That is also a necessary set up step.

**Comment by TobiasFroberg** [comment]
> 🤔 interesting. Oh, are your ecto repos in `config :my_app, ecto_repos: [...]`? That is also a necessary set up step.

Yep, I also have that!

**Comment by zachdaniel** [comment]
🤔 🤔 this is pretty strange. Would you be able to provide a sample project that reproduces this behavior?

**Comment by TobiasFroberg** [comment]
Have a look here: https://github.com/TobiasFroberg/ash_postgres_357

> ➜  helpdesk git:(main) mix ash_postgres.migrate                         
> ➜  helpdesk git:(main) 

But if I do:
> ➜  helpdesk git:(main) mix ash_postgres.migrate --domains Helpdesk.Support
> 
> 15:25:00.954 [info] == Running 20240724131330 Helpdesk.Repo.Migrations.AddColumnsToCompanyTable.up/0 forward

Please note I'm still pretty new to Ash so I might'v done something wrong while trying to create a small reproduction.

**Comment by zachdaniel** [comment]
Fixed in e49b678351495d0b6b9e50252912b5247092d8d1
