### ISSUE TITLE
Installer doesn't add `mix test` alias that sets up the DB and runs migrations.

### ISSUE THREAD

**Issue by jimsynz** [ash-project/ash_postgres#391]
It needs to add the following alias into the `mix.exs` if it doesn't already exist.

```elixir
def project do
  [
    # ...
    aliases: aliases(),
    # ...
  ]
end

def aliases do
  [
    test: ["ash.setup --quiet", "test"]
  ]
end
```

**Comment by zachdaniel** [comment]
![CleanShot 2024-09-23 at 13 24 35](https://github.com/user-attachments/assets/c6507559-f6c9-41f2-b58f-ad3b82ed31b6)

Okay, I've added tools for this in igniter. We now also remove some of the Ecto-specific stuff that it makes sense to remove :) Will be pushing this shortly.
