### ISSUE TITLE
Add --exit option to migration generator

### ISSUE THREAD

**Issue by zimt28** [ash-project/ash_postgres#40]
Would make sense to add an `--exit` option to `Mix.Tasks.AshPostgres.GenerateMigrations`? It could then be used in CIs and fail if resources and migrations don't fit together. The big issue I see here is that the CI would have to be changed every time there's a new api.

**Comment by zimt28** [comment]
`--exit` might not be the best name though. Maybe `--enforce-latest-migrations`?
This is how other libraries do it:
```elixir
[
  "format --check-formatted",
  "credo --strict",
  "sobelow --exit",
  "dialyzer --halt-exit-status"
]
```

**Comment by zachdaniel** [comment]
Yeah, I think `ash_postgres.generate_migrations --check-generated` would be a good name for the flag. We'd then just have to add a check after we've generated a full list of "operations" and if there are any, check the `--check-generated` flag and bail if that is set.

**Comment by zachdaniel** [comment]
A good idea :)

**Comment by zimt28** [comment]
This has been added via #43 ✅
