### ISSUE TITLE
Migration example does not work for multi tenancy

### ISSUE THREAD

**Issue by cinoss** [ash-project/ash_postgres#407]
**Describe the bug**
https://hexdocs.pm/ash_postgres/migrations-and-tasks.html#running-migrations-in-production

```elixir
    path =
      "priv/"
      |> Path.join(repo_name)
      |> Path.join("tenant_migrations")
```
This seems to be similar to https://github.com/elixir-ecto/ecto_sql/blob/v3.12.1/lib/ecto/migrator.ex#L194
but the app path part is missing.

we can update the doc to use `Ecto.Migrator.migrations_path` instead

**Comment by zachdaniel** [comment]
👍 would you be interested in PRing a change here? Want to also verify that the code is working in a real example before updating.

**Comment by cinoss** [comment]
@zachdaniel  It is working for my project. For the PR, do we want some test for it or just updating the docs is ok?

**Comment by zachdaniel** [comment]
Just docs 👍
