### ISSUE TITLE
rename/3 is used inside alter/2

### ISSUE THREAD

**Issue by Awlexus** [ash-project/ash_postgres#41]
**Describe the bug**
I tried creating a migration where I rename one field, but the resulting migration created the following code.
```elixir
  def up() do
    alter table(:streaming_profile) do
      rename(table(:streaming_profile), :url, to: :profile_id)
    end
  end

  def down() do
    alter table(:streaming_profile) do
      rename(table(:streaming_profile), :profile_id, to: :url)
    end
  end
```

**To Reproduce**
1. Create a resource
2. Create migrations
3. rename one field
4. Create migrations again

**Expected behavior**
The rename statement should have been defined outside of the alter block
```elixir
  def up() do
    rename(table(:streaming_profile), :url, to: :profile_id)
  end

  def down() do
    rename(table(:streaming_profile), :profile_id, to: :url)
  end
```

** Runtime
- Ash Version: 1.26.13
- Ash Postgres Version: 0.28.1

**Comment by zachdaniel** [comment]
Just pushed a fix up, releasing in `v0.29.6`
