### ISSUE TITLE
Ecto.Query.CompileError when using no_attributes? true in relationships

### ISSUE THREAD

**Issue by rapidfsub** [ash-project/ash_postgres#412]
**Describe the bug**
When using `no_attributes? true` in relationships, I encounter `Ecto.Query.CompileError` frequently.

There are three resources.
- Store
has_many :inventories
- Product
has_many :inventories
- Inventory (join table resource)
belongs_to :store
belongs_to :product

- relationship code in Product
```
defmodule SonetLib.SevenEleven.Product do
  relationships do
    has_many :stores, SevenEleven.Store do
      no_attributes? true
      filter expr(inventories.product_id == parent(id))
    end

    has_many :stores_alt1, SevenEleven.Store do
      no_attributes? true
      filter expr(inventories.store_id == parent(inventories.store_id))
    end

    has_many :stores_alt2, SevenEleven.Store do
      no_attributes? true
      filter expr(id == parent(inventories.store_id))
    end
  end
end
```
I think these three relationships are equivalent, but only the first one works.
And the other two relationships raise error when loading them.

- stacktrace
```
  1) test relationships stores (SonetLib.SevenEleven.ProductTest)
     test/sonet_lib/seven_eleven/product_test.exs:24
     ** (Ecto.Query.CompileError) only one distinct expression is allowed in query
     code: Ashex.load!(product, [:stores_alt1])
     stacktrace:
       (ash_postgres 2.4.11) lib/data_layer.ex:1102: AshPostgres.DataLayer.lateral_join_query/3
       (ash_postgres 2.4.11) lib/data_layer.ex:961: AshPostgres.DataLayer.run_query_with_lateral_join/4
       (ash 3.4.35) lib/ash/actions/read/read.ex:2650: Ash.Actions.Read.run_query/4
       (ash 3.4.35) lib/ash/actions/read/read.ex:542: anonymous fn/8 in Ash.Actions.Read.do_read/5
       (ash 3.4.35) lib/ash/actions/read/read.ex:886: Ash.Actions.Read.maybe_in_transaction/3
       (ash 3.4.35) lib/ash/actions/read/read.ex:269: Ash.Actions.Read.do_run/3
       (ash 3.4.35) lib/ash/actions/read/read.ex:81: anonymous fn/3 in Ash.Actions.Read.run/3
       (ash 3.4.35) lib/ash/actions/read/read.ex:80: Ash.Actions.Read.run/3
       (ash 3.4.35) lib/ash/actions/read/relationships.ex:413: anonymous fn/2 in Ash.Actions.Read.Relationships.do_fetch_related_records/4
       (ash 3.4.35) lib/ash/actions/read/relationships.ex:65: Ash.Actions.Read.Relationships.fetch_related_records/4
       (ash 3.4.35) lib/ash/actions/read/relationships.ex:24: Ash.Actions.Read.Relationships.load/4
       (ash 3.4.35) lib/ash/actions/read/read.ex:298: Ash.Actions.Read.do_run/3
       (ash 3.4.35) lib/ash/actions/read/read.ex:81: anonymous fn/3 in Ash.Actions.Read.run/3
       (ash 3.4.35) lib/ash.ex:1859: Ash.load/3
       (ash 3.4.35) lib/ash.ex:1813: Ash.load/3
       (ash 3.4.35) lib/ash.ex:1754: Ash.load!/3
       test/sonet_lib/seven_eleven/product_test.exs:28: (test)
```

**To Reproduce**
I will attach some links to my public repo.
You can reproduce it easily with test code.

1. resource `Store`
https://github.com/rapidfsub/sonet/blob/develop/test/support/lib/sonet_lib/seven_eleven/store.ex
2. resource `Product`
https://github.com/rapidfsub/sonet/blob/develop/test/support/lib/sonet_lib/seven_eleven/product.ex
3. resource `Inventory` (join table resource for `Store` and `Product`)
https://github.com/rapidfsub/sonet/blob/develop/test/support/lib/sonet_lib/seven_eleven/inventory.ex
4. test code for reproduction
https://github.com/rapidfsub/sonet/blob/develop/test/sonet_lib/seven_eleven/product_test.exs#L24

I know I can use `many_to_many` feature in this example,
but I need a simple example to show the bug in `no_attributes? true` feature.

**Expected behavior**
- relationships works without any error

**Runtime**
 - Elixir version
1.17.0-otp-27
 - Erlang version
27.0
 - OS
mac os sequoia
 - Ash version
 3.4.35
 - any related extension versions
 ash_postgres 2.4.11

**Additional context**
I wrote a question about this in elixir forum below.
https://elixirforum.com/t/how-to-write-relationships-with-no-attributes/67042

**Comment by zachdaniel** [comment]
Fixed in `main`.
