### ISSUE TITLE
In `context` multitenant, schema for related table is missing when there is policy using expr on the relation

### ISSUE THREAD

**Issue by cinoss** [ash-project/ash_postgres#421]
**Describe the bug**

In `context` multitenant, schema for table is missing when there is policy using expr on relation

**To Reproduce**

update the test to following

```patch
--- a/test/support/multitenancy/resources/org.ex
+++ b/test/support/multitenancy/resources/org.ex
@@ -18,7 +18,7 @@ defmodule AshPostgres.MultitenancyTest.Org do

   policies do
     policy action(:has_policies) do
-      authorize_if(relates_to_actor_via(:owner))
+      authorize_if(expr(^actor(:id) == posts.user.id))
     end
```

we will then get

```
     * ** (Postgrex.Error) ERROR 42P01 (undefined_table) relation "public.multitenant_posts" does not exist

         query: SELECT DISTINCT ON (m0."id") m0."id", m0."name", m0."owner_id" FROM "multitenant_orgs" AS m0 INNER JOIN "public"."multitenant_posts" AS m1 ON m0."id" = m1."org_id" INNER JOIN "public"."users" AS u2 ON m1."user_id" = u2."id" WHERE (m0."id"::uuid = $1::uuid) AND ($2::uuid = u2."id"::uuid)
```

**Expected behavior**
`multitenant_posts` should not be from public but from a tenant schema

** Runtime
 - Elixir version: 1.17.2-otp-27
 - Erlang version: 27.0.1
 - OS: Macos 15.0.1 (24A348)
 - Ash version
 - any related extension versions

**Additional context**

**Comment by cinoss** [comment]
Current patch for my problem which is count for graphql keyset
https://github.com/ash-project/ash/compare/main...cinoss:ash:main
https://github.com/ash-project/ash_sql/compare/main...cinoss:ash_sql:main

**Comment by zachdaniel** [comment]
I merged your patch w/ some small changes that should avoid the need for the `ash_sql` changes. Can you try it out?

**Comment by cinoss** [comment]
> I merged your patch w/ some small changes that should avoid the need for the `ash_sql` changes. Can you try it out?

Sure, let me give it a try

**Comment by cinoss** [comment]
@zachdaniel I am running on ash main it seems to work fine. Look forward to the next release
