### ISSUE TITLE
Allow the `migration_path` and `snapshot_path` to be configured per repo.

### ISSUE THREAD

**Issue by jimsynz** [ash-project/ash_postgres#426]
An APS client with a number of repos in their app recently asked if it's possible to have ash_postgres honour Ecto's `:priv` config value. I think we should both honour that value, but also allow configuration of the migration path and snapshot path on a per-repo basis.

**Comment by zachdaniel** [comment]
@jimsynz is there a reproduction or a specific example of the issue/case where we weren't honoring this option? Looking at the code:

```elixir
  def derive_migrations_path(repo) do
    config = repo.config()
    priv = config[:priv] || "priv/#{repo |> Module.split() |> List.last() |> Macro.underscore()}"
    app = Keyword.fetch!(config, :otp_app)
    Application.app_dir(app, Path.join(priv, "migrations"))

  ...
```

```elixir
  def derive_tenant_migrations_path(repo) do
    config = repo.config()
    priv = config[:priv] || "priv/#{repo |> Module.split() |> List.last() |> Macro.underscore()}"
    app = Keyword.fetch!(config, :otp_app)
    Application.app_dir(app, Path.join(priv, "tenant_migrations"))
    ...
```

So it's clear we're at least attempting to honor the repo's `priv` config value. Will need more info on what specifically illustrated that we were not.

**Comment by zachdaniel** [comment]
But we do allow the `migrations_path` and `tenant_migrations_path`, so from what I can tell its just missing corresponding behavior in the migration generator.

```elixir
    opts[:migrations_path] || repo.config()[:migrations_path] || derive_migrations_path(repo)
  end

  def tenant_migrations_path(opts, repo) do
    opts[:migrations_path] || repo.config()[:tenant_migrations_path] ||
      derive_tenant_migrations_path(repo)
  end
```
