### ISSUE TITLE
Set the default PostgreSQL version to the one on the current system

### ISSUE THREAD

**Issue by wintermeyer** [ash-project/ash_postgres#430]
Every time I use `mix igniter.install ash_postgres` I run into this situation:

```bash
What is the minimum PostgreSQL version you will be using?

AshPostgres uses this information when generating queries and migrations,
to choose the best available features for your version of PostgreSQL.


Please enter the version in the format major.minor.patch (e.g. 13.4.0)

Default: 16.0.0

❯
```

Of course I can run `psql --version` in an other terminal to find the answer to that question (at least for my development system) but I don't want to. I am using igniter to make my life easier.

Why doesn't igniter try to run `psql --version` or something similar in the background and give me something like this as an option: 

```bash
What is the minimum PostgreSQL version you will be using?

AshPostgres uses this information when generating queries and migrations,
to choose the best available features for your version of PostgreSQL.

On this system we found a PostgreSQL with the version number 14.13

Please enter the version in the format major.minor.patch (e.g. 13.4.0)

Default: 14.13.0

❯
```

This will make the live of 99% of all developers easier. And the other 1% doesn't have any disadvantages.

**Comment by wojtekmach** [comment]
Note `psql --version` returns the _client_ version. I'd expect for vast majority of users the client and server versions would match but it's not a guarantee in more complicated setups, e.g. having a single psql client but multiple pg servers locally. You can use Ecto/Postgrex without psql (say you have your db in docker container) too. Just fyi!

**Comment by wintermeyer** [comment]
```bash
psql -U postgres -c "SHOW server_version;" -t
```

Should do the trick. And YES, this might not run on all systems. Yes, you could have a different password. Yes, you could create a fresh Ash project on a system which doesn't even have PostgreSQL installed. All true. The script has to catch those problems. But for more than 80% this is a time saver because they have a standard installation.

**Comment by zachdaniel** [comment]
I think the main thing here is that we're only proposing a default value for a configuration that can be changed later on. So using the command you provided as the default value as opposed to just `16.0.0` should be totally fine. It is at least slightly more likely to be accurate as our proposed default.

**Comment by zachdaniel** [comment]
This has been implemented using the `postgres` command which should show the server version. Only works on some systems, but that is the nature of it.

Finally, the other change that has been made is that we now just show a notice that the user may want to configure a version, regardless of whether or not we successfully found one. This reduces friction of initial setup.
