### ISSUE TITLE
Default values

### ISSUE THREAD

**Issue by zimt28** [ash-project/ash_postgres#52]
The migration generator uses `inspect/1` to generate default values. In case of `:decimal` types (and maybe others) this leads to invalid defaults:

```
iex(2)> Decimal.new(0) |> to_string()
"0"
iex(3)> Decimal.new(0) |> inspect()
"#Decimal<0>"
```

**Comment by zachdaniel** [comment]
Alright, so struct defaults are now passed through `to_string()`. This should cover most of the relevant cases, but likely not all of them. We can tackle those on a case-by-case basis.
