### ISSUE TITLE
tenant_schema callback

### ISSUE THREAD

**Issue by zimt28** [ash-project/ash_postgres#58]
Proposal: Add a `tenant_schema/1` callback to `AshPostgres.Repo` which takes any input from a `tenant: param` and returns a schema string.

**Comment by zachdaniel** [comment]
We won't be able to accept any arbitrary value, as currently the tenant is expected to be a string everywhere in the framework. What we could potentially do is have a `to_tenant` protocol that does this work at the boundary.

**Comment by zachdaniel** [comment]
The `to_tenant` protocol has been added to ash core in 30
