### ISSUE TITLE
Migration generator shows wrong summary

### ISSUE THREAD

**Issue by zimt28** [ash-project/ash_postgres#68]
Example, the generator actually created 5 files:
```
* creating priv/repo/tenant_migrations/20210727125616_migrate_resources2.exs
No changes detected, so no migrations or snapshots have been created.
```

**Comment by zimt28** [comment]
Closing this, as the output is actually correct: The first line refers to tenant migrations while the second one refers to public migrations. Some headings and an empty line between those might be nice though :)

**Comment by zachdaniel** [comment]
<img width="687" alt="CleanShot 2021-07-27 at 11 19 52@2x" src="https://user-images.githubusercontent.com/5722339/127181006-6f16790c-87d9-460f-832a-d6f505f7f9ad.png">
Improved the formatting/information contained in the output there, agreed that it was confusing otherwise :D
