### ISSUE TITLE
Generate indexes for foreign keys

### ISSUE THREAD

**Issue by michaelst** [ash-project/ash_postgres#71]
When generating ecto migrations we should consider also generating the indexes for foreign keys

**Comment by michaelst** [comment]
looks like they should be generated here https://hexdocs.pm/ash_postgres/0.41.0-rc.5/AshPostgres.DataLayer.html#module-custom_indexes

**Comment by kreba** [comment]
Helpful hint for other newbies like me: 
You have to add the `custom_indexes` block inside the `postgres` DSL block.

```
defmodule MyApp.Plant do
  use Ash.Resource,
    data_layer: AshPostgres.DataLayer

  postgres do
    repo MyApp.Repo
    table "plants"

    custom_indexes do
      index :forest_id
    end
  end

  relationships do
    belongs_to :forest, MyApp.Forest, allow_nil?: false
  end
end
```
