### ISSUE TITLE
outstanding issues with dynamic refactor

### ISSUE THREAD

**Issue by kernel-io** [ash-project/ash_postgres#81]
As discussed on Discord here are the outstanding issues I am encountering in my application while using the dynamic refactor of ash postgres.

1) Inability to use DB enums as Ash explicitly casts the bindings to a varchar instead of just leaving it uncast - i.e: `SELECT * FROM burgers WHERE status = $1::varchar` (instead of just `= $1`) - also the `storage_type` override on Ash.Type has no effect on this.

2) Ash gets confused while trying to load an aggregate that has a filter on it 
`count :total_leased_count,
          :assets,
          filter: expr(is_nil(active_order_service.id) == false)`

In my case I have AssetType which has many Assets, which in turn has one active OrderService (`has_one :active_order_service, OrderService, filter: expr(fragment("? @> now()", period))`), I have a count aggregate defined on AssetType which counts the number of Assets with an active OrderService, OrderService has a range type column called period. 

error is `unknown error: {%Ecto.SubQueryError{exception: %Ecto.QueryError{message: \"could not find named binding 'as(nil)')` while trying to load the AssetType with the count 

3) I have previously needed to define the filter on the aggregate and relationship for it to work correctly, I can't tell if this has been fixed as point 2 is blowing up first.

4) There was an issue with GROUP BY on aggregates, which I think has been resolved, but I can't fully test because of `2`.

**Comment by kernel-io** [comment]
update: Enums are still not fixed, however the query builder seems to be respecting the `storage_type` callback now at least. Postgres still complaining though.

**Comment by zachdaniel** [comment]
@kernel-io is there a new error message for the storage_type issue?

**Comment by kernel-io** [comment]
postgres saying the type doesn't exist (when it does)

**Comment by kernel-io** [comment]
okay, so I have my custom types defined in each tenant's schema, the issue is that we aren't qualifying which schema the custom type is defined in, so postgres is looking for it in the db roles search_path, which doesn't contain that custom type. would it be easy to qualify the type?

**Comment by zachdaniel** [comment]
I think the primary thing we could do here is to have a callback like `def cast_in_query?(), do: false` on the type. Alternatively, we could have ash_postgres set the search path before running a query to include the tenant, but I'm not as big of a fan of that option. We could potentially tell ash to scope the type to a given prefix, but that also comes with issues, because its not necessarily given that a query is *entirely* in a single tenant's schema. It may also be partially using things from the main schema, and potentially from other tenants (in the future, not right now).

**Comment by zachdaniel** [comment]
Okay, the latest master has that fix, so you can add `def cast_in_query?, do: false` to your enum types.

**Comment by kernel-io** [comment]
all sorted :)
