### ISSUE TITLE
`repo` is not formatting correctly

### ISSUE THREAD

**Issue by joshprice** [ash-project/ash_postgres#84]
I've setup formatters for `ash` and `ash_postgres`

```elixir
  import_deps: [:ecto, :phoenix, :surface, :ash, :ash_postgres],
```

 but don't see repo formatting correctly 

```elixir
  postgres do
    repo(MyApp.Repo)
    table "account"
  end
```

Should see:

```elixir
  postgres do
    repo MyApp.Repo
    table "account"
  end
```
 
**Runtime**

erlang 24.3.3
elixir 1.13.3-otp-24
ash master, 1.51
ash_postgres 0.41.7

**Additional context**

Have checked the formatters and ash contains `table` but not `repo`:

https://github.com/ash-project/ash/blob/master/.formatter.exs#L108

ash_postgres formatter has `table` and `repo`:

https://github.com/ash-project/ash_postgres/blob/master/.formatter.exs#L31
https://github.com/ash-project/ash_postgres/blob/master/.formatter.exs#L29

**Comment by zachdaniel** [comment]
This may be an elixir_ls issue. I have problems with deps and formatting in this way sometimes. I've had to turn off the formatting on save, unfortunately. In my experience there are issues while its compiling with formatting properly. Often I have to delete my `.elixir_ls` folder as well. I don't *think* that this is an ash_postgres issue, but I'll leave this open and you can try deleting your `.elixir_ls` folder to see if that resolves it.

**Comment by joshprice** [comment]
I'm using elixir_ls in VS Code so yes this could be the issue. However you pointed out that the formatter won't remove parens, only "not add them" and I think this may be the issue.
