### ISSUE TITLE
`uuid_primary_key` should allow autogenerated IDs

### ISSUE THREAD

**Issue by joshprice** [ash-project/ash_postgres#85]
When defining UUID primary keys there doesn't seem to be a way to specify the keys to autogenerate. For example:

```elixir
  attributes do
    uuid_primary_key :id
  end
``` 

generates the following migration

```elixir
  def up do
    create table(:account, primary_key: false) do
      add :id, :uuid, null: false, primary_key: true
      ...
```

It'd be great to be able to opt into (or even default to) autogeneration:

```elixir
  def up do
    create table(:account, primary_key: false) do
      add :id, :uuid, null: false, primary_key: true, autogenerate: true
      ...
```

If we opt in to auto generation:

```elixir
  attributes do
    uuid_primary_key :id, autogenerate: true
  end
``` 

Or if we default to auto generation, this would allow opt-out

```elixir
  attributes do
    uuid_primary_key :id, autogenerate: false
  end
``` 

Obviously opt-in is more backward compatible but I suspect that autogenerate should probably be the default?

**Comment by zachdaniel** [comment]
So the general pattern for this in AshPostgres is to add the following to your repo:

```elixir
def installed_extensions do
  ["uuid-ossp"]
end
```

This will cause the migration generator to generate default uuids at the database level. Otherwise, all we can do is generate them at the application level which I think is all that ecto can do as well.
