### ISSUE TITLE
Keep track of binding count during query building

### ISSUE THREAD

**Issue by zachdaniel** [ash-project/ash_postgres#9]
Right now, every time we add an expression we count the bindings, see `filter_value_to_expr` in `data_layer.ex`. We should just keep track of the count alongside the list.

**Comment by michaelst** [comment]
is this issue out of date? I'm not seeing `filter_value_to_expr` anywhere in the code

**Comment by zachdaniel** [comment]
There are still a few places where we're counting params, but it doesn't really matter. Its a bunch of counts of small lists, not worth optimizing unless it becomes an issue :) Good catch.
