### ISSUE TITLE
Custom schema does not get carried over to underlying SQL queries

### ISSUE THREAD

**Issue by fredwu** [ash-project/ash_postgres#96]
**Describe the bug**

When an Ash resource is defined using a custom schema (via `schema("blah")`), when doing queries, the underlying queries don't seem to take the custom schema into account.

**To Reproduce**

Add `schema("anything_but_public")` to a resource.

**Expected behavior**

Queries such as:

```elixir
MyAshResource
|> Ash.Query.filter(user_id: user.id)
|> Api.read_one!()
```

should work, but it doesn't. With the following error:

```
** (Ash.Error.Unknown)

* ** (Postgrex.Error) ERROR 42P01 (undefined_table) relation "blah" does not exist

    query: SELECT f0."id", f0."source", f0."money", f0."status", f0."metadata", f0."inserted_at", f0."updated_at", f0."user_id" FROM "blah" AS f0 WHERE (f0."user_id" = $1::uuid)
```

** Runtime
 - Elixir version 1.13.4
 - Erlang version 24.3.4
 - OS macOS 12.4
 - Ash version 1.52.0-rc.4
 - Ash Posgres 610e38812de081948a2edc7a00312daf755f3c37

**Additional context**

Everything worked fine before changing the schema. After running `mix ash_postgres.generate_migrations`, the migration file correctly contains `prefix: "blah"`. Resetting the DB was also successful, can see the new schema and its tables.

**Comment by zachdaniel** [comment]
Fixed in d04fd201f2f7df808104fa83228a2febff367ff1

Thanks for the report!
